// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://taalnjwwgwbtmahxewpa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhYWxuand3Z3didG1haHhld3BhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg5NjQyOTMsImV4cCI6MjA1NDU0MDI5M30.ApzpGkD1kpBfw7LBRs6jzKUf9HNklyJ76KaRCSa8fok";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);